services:
  mongo:
    image: mongo:latest
    container_name: famos-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: famos
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: famos-redis
    ports:
      - "6380:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/data
